// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: udppeer.proto

package udppeer;

public final class UDPPeerMessages {
  private UDPPeerMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Type1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Type1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string strData = 1;</code>
     */
    java.lang.String getStrData();
    /**
     * <code>string strData = 1;</code>
     */
    com.google.protobuf.ByteString
        getStrDataBytes();
  }
  /**
   * Protobuf type {@code Type1}
   */
  public  static final class Type1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Type1)
      Type1OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Type1.newBuilder() to construct.
    private Type1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Type1() {
      strData_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Type1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              strData_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return udppeer.UDPPeerMessages.internal_static_Type1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return udppeer.UDPPeerMessages.internal_static_Type1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              udppeer.UDPPeerMessages.Type1.class, udppeer.UDPPeerMessages.Type1.Builder.class);
    }

    public static final int STRDATA_FIELD_NUMBER = 1;
    private volatile java.lang.Object strData_;
    /**
     * <code>string strData = 1;</code>
     */
    public java.lang.String getStrData() {
      java.lang.Object ref = strData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        strData_ = s;
        return s;
      }
    }
    /**
     * <code>string strData = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStrDataBytes() {
      java.lang.Object ref = strData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStrDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, strData_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStrDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, strData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof udppeer.UDPPeerMessages.Type1)) {
        return super.equals(obj);
      }
      udppeer.UDPPeerMessages.Type1 other = (udppeer.UDPPeerMessages.Type1) obj;

      boolean result = true;
      result = result && getStrData()
          .equals(other.getStrData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STRDATA_FIELD_NUMBER;
      hash = (53 * hash) + getStrData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static udppeer.UDPPeerMessages.Type1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static udppeer.UDPPeerMessages.Type1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static udppeer.UDPPeerMessages.Type1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static udppeer.UDPPeerMessages.Type1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static udppeer.UDPPeerMessages.Type1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static udppeer.UDPPeerMessages.Type1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static udppeer.UDPPeerMessages.Type1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static udppeer.UDPPeerMessages.Type1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static udppeer.UDPPeerMessages.Type1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static udppeer.UDPPeerMessages.Type1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static udppeer.UDPPeerMessages.Type1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static udppeer.UDPPeerMessages.Type1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(udppeer.UDPPeerMessages.Type1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Type1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Type1)
        udppeer.UDPPeerMessages.Type1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return udppeer.UDPPeerMessages.internal_static_Type1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return udppeer.UDPPeerMessages.internal_static_Type1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                udppeer.UDPPeerMessages.Type1.class, udppeer.UDPPeerMessages.Type1.Builder.class);
      }

      // Construct using udppeer.UDPPeerMessages.Type1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        strData_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return udppeer.UDPPeerMessages.internal_static_Type1_descriptor;
      }

      public udppeer.UDPPeerMessages.Type1 getDefaultInstanceForType() {
        return udppeer.UDPPeerMessages.Type1.getDefaultInstance();
      }

      public udppeer.UDPPeerMessages.Type1 build() {
        udppeer.UDPPeerMessages.Type1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public udppeer.UDPPeerMessages.Type1 buildPartial() {
        udppeer.UDPPeerMessages.Type1 result = new udppeer.UDPPeerMessages.Type1(this);
        result.strData_ = strData_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof udppeer.UDPPeerMessages.Type1) {
          return mergeFrom((udppeer.UDPPeerMessages.Type1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(udppeer.UDPPeerMessages.Type1 other) {
        if (other == udppeer.UDPPeerMessages.Type1.getDefaultInstance()) return this;
        if (!other.getStrData().isEmpty()) {
          strData_ = other.strData_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        udppeer.UDPPeerMessages.Type1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (udppeer.UDPPeerMessages.Type1) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object strData_ = "";
      /**
       * <code>string strData = 1;</code>
       */
      public java.lang.String getStrData() {
        java.lang.Object ref = strData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          strData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string strData = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStrDataBytes() {
        java.lang.Object ref = strData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          strData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string strData = 1;</code>
       */
      public Builder setStrData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        strData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string strData = 1;</code>
       */
      public Builder clearStrData() {
        
        strData_ = getDefaultInstance().getStrData();
        onChanged();
        return this;
      }
      /**
       * <code>string strData = 1;</code>
       */
      public Builder setStrDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        strData_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Type1)
    }

    // @@protoc_insertion_point(class_scope:Type1)
    private static final udppeer.UDPPeerMessages.Type1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new udppeer.UDPPeerMessages.Type1();
    }

    public static udppeer.UDPPeerMessages.Type1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Type1>
        PARSER = new com.google.protobuf.AbstractParser<Type1>() {
      public Type1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Type1(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Type1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Type1> getParserForType() {
      return PARSER;
    }

    public udppeer.UDPPeerMessages.Type1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Type2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Type2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 intData = 1;</code>
     */
    int getIntData();
  }
  /**
   * Protobuf type {@code Type2}
   */
  public  static final class Type2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Type2)
      Type2OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Type2.newBuilder() to construct.
    private Type2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Type2() {
      intData_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Type2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              intData_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return udppeer.UDPPeerMessages.internal_static_Type2_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return udppeer.UDPPeerMessages.internal_static_Type2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              udppeer.UDPPeerMessages.Type2.class, udppeer.UDPPeerMessages.Type2.Builder.class);
    }

    public static final int INTDATA_FIELD_NUMBER = 1;
    private int intData_;
    /**
     * <code>int32 intData = 1;</code>
     */
    public int getIntData() {
      return intData_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (intData_ != 0) {
        output.writeInt32(1, intData_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (intData_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, intData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof udppeer.UDPPeerMessages.Type2)) {
        return super.equals(obj);
      }
      udppeer.UDPPeerMessages.Type2 other = (udppeer.UDPPeerMessages.Type2) obj;

      boolean result = true;
      result = result && (getIntData()
          == other.getIntData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INTDATA_FIELD_NUMBER;
      hash = (53 * hash) + getIntData();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static udppeer.UDPPeerMessages.Type2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static udppeer.UDPPeerMessages.Type2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static udppeer.UDPPeerMessages.Type2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static udppeer.UDPPeerMessages.Type2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static udppeer.UDPPeerMessages.Type2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static udppeer.UDPPeerMessages.Type2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static udppeer.UDPPeerMessages.Type2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static udppeer.UDPPeerMessages.Type2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static udppeer.UDPPeerMessages.Type2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static udppeer.UDPPeerMessages.Type2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static udppeer.UDPPeerMessages.Type2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static udppeer.UDPPeerMessages.Type2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(udppeer.UDPPeerMessages.Type2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Type2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Type2)
        udppeer.UDPPeerMessages.Type2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return udppeer.UDPPeerMessages.internal_static_Type2_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return udppeer.UDPPeerMessages.internal_static_Type2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                udppeer.UDPPeerMessages.Type2.class, udppeer.UDPPeerMessages.Type2.Builder.class);
      }

      // Construct using udppeer.UDPPeerMessages.Type2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        intData_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return udppeer.UDPPeerMessages.internal_static_Type2_descriptor;
      }

      public udppeer.UDPPeerMessages.Type2 getDefaultInstanceForType() {
        return udppeer.UDPPeerMessages.Type2.getDefaultInstance();
      }

      public udppeer.UDPPeerMessages.Type2 build() {
        udppeer.UDPPeerMessages.Type2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public udppeer.UDPPeerMessages.Type2 buildPartial() {
        udppeer.UDPPeerMessages.Type2 result = new udppeer.UDPPeerMessages.Type2(this);
        result.intData_ = intData_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof udppeer.UDPPeerMessages.Type2) {
          return mergeFrom((udppeer.UDPPeerMessages.Type2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(udppeer.UDPPeerMessages.Type2 other) {
        if (other == udppeer.UDPPeerMessages.Type2.getDefaultInstance()) return this;
        if (other.getIntData() != 0) {
          setIntData(other.getIntData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        udppeer.UDPPeerMessages.Type2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (udppeer.UDPPeerMessages.Type2) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int intData_ ;
      /**
       * <code>int32 intData = 1;</code>
       */
      public int getIntData() {
        return intData_;
      }
      /**
       * <code>int32 intData = 1;</code>
       */
      public Builder setIntData(int value) {
        
        intData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 intData = 1;</code>
       */
      public Builder clearIntData() {
        
        intData_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Type2)
    }

    // @@protoc_insertion_point(class_scope:Type2)
    private static final udppeer.UDPPeerMessages.Type2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new udppeer.UDPPeerMessages.Type2();
    }

    public static udppeer.UDPPeerMessages.Type2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Type2>
        PARSER = new com.google.protobuf.AbstractParser<Type2>() {
      public Type2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Type2(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Type2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Type2> getParserForType() {
      return PARSER;
    }

    public udppeer.UDPPeerMessages.Type2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Type1 t1 = 1;</code>
     */
    boolean hasT1();
    /**
     * <code>.Type1 t1 = 1;</code>
     */
    udppeer.UDPPeerMessages.Type1 getT1();
    /**
     * <code>.Type1 t1 = 1;</code>
     */
    udppeer.UDPPeerMessages.Type1OrBuilder getT1OrBuilder();

    /**
     * <code>.Type2 t2 = 2;</code>
     */
    boolean hasT2();
    /**
     * <code>.Type2 t2 = 2;</code>
     */
    udppeer.UDPPeerMessages.Type2 getT2();
    /**
     * <code>.Type2 t2 = 2;</code>
     */
    udppeer.UDPPeerMessages.Type2OrBuilder getT2OrBuilder();

    public udppeer.UDPPeerMessages.Packet.MsgCase getMsgCase();
  }
  /**
   * Protobuf type {@code Packet}
   */
  public  static final class Packet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Packet)
      PacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Packet() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              udppeer.UDPPeerMessages.Type1.Builder subBuilder = null;
              if (msgCase_ == 1) {
                subBuilder = ((udppeer.UDPPeerMessages.Type1) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(udppeer.UDPPeerMessages.Type1.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((udppeer.UDPPeerMessages.Type1) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 1;
              break;
            }
            case 18: {
              udppeer.UDPPeerMessages.Type2.Builder subBuilder = null;
              if (msgCase_ == 2) {
                subBuilder = ((udppeer.UDPPeerMessages.Type2) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(udppeer.UDPPeerMessages.Type2.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((udppeer.UDPPeerMessages.Type2) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 2;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return udppeer.UDPPeerMessages.internal_static_Packet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return udppeer.UDPPeerMessages.internal_static_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              udppeer.UDPPeerMessages.Packet.class, udppeer.UDPPeerMessages.Packet.Builder.class);
    }

    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public enum MsgCase
        implements com.google.protobuf.Internal.EnumLite {
      T1(1),
      T2(2),
      MSG_NOT_SET(0);
      private final int value;
      private MsgCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgCase forNumber(int value) {
        switch (value) {
          case 1: return T1;
          case 2: return T2;
          case 0: return MSG_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MsgCase
    getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public static final int T1_FIELD_NUMBER = 1;
    /**
     * <code>.Type1 t1 = 1;</code>
     */
    public boolean hasT1() {
      return msgCase_ == 1;
    }
    /**
     * <code>.Type1 t1 = 1;</code>
     */
    public udppeer.UDPPeerMessages.Type1 getT1() {
      if (msgCase_ == 1) {
         return (udppeer.UDPPeerMessages.Type1) msg_;
      }
      return udppeer.UDPPeerMessages.Type1.getDefaultInstance();
    }
    /**
     * <code>.Type1 t1 = 1;</code>
     */
    public udppeer.UDPPeerMessages.Type1OrBuilder getT1OrBuilder() {
      if (msgCase_ == 1) {
         return (udppeer.UDPPeerMessages.Type1) msg_;
      }
      return udppeer.UDPPeerMessages.Type1.getDefaultInstance();
    }

    public static final int T2_FIELD_NUMBER = 2;
    /**
     * <code>.Type2 t2 = 2;</code>
     */
    public boolean hasT2() {
      return msgCase_ == 2;
    }
    /**
     * <code>.Type2 t2 = 2;</code>
     */
    public udppeer.UDPPeerMessages.Type2 getT2() {
      if (msgCase_ == 2) {
         return (udppeer.UDPPeerMessages.Type2) msg_;
      }
      return udppeer.UDPPeerMessages.Type2.getDefaultInstance();
    }
    /**
     * <code>.Type2 t2 = 2;</code>
     */
    public udppeer.UDPPeerMessages.Type2OrBuilder getT2OrBuilder() {
      if (msgCase_ == 2) {
         return (udppeer.UDPPeerMessages.Type2) msg_;
      }
      return udppeer.UDPPeerMessages.Type2.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgCase_ == 1) {
        output.writeMessage(1, (udppeer.UDPPeerMessages.Type1) msg_);
      }
      if (msgCase_ == 2) {
        output.writeMessage(2, (udppeer.UDPPeerMessages.Type2) msg_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (udppeer.UDPPeerMessages.Type1) msg_);
      }
      if (msgCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (udppeer.UDPPeerMessages.Type2) msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof udppeer.UDPPeerMessages.Packet)) {
        return super.equals(obj);
      }
      udppeer.UDPPeerMessages.Packet other = (udppeer.UDPPeerMessages.Packet) obj;

      boolean result = true;
      result = result && getMsgCase().equals(
          other.getMsgCase());
      if (!result) return false;
      switch (msgCase_) {
        case 1:
          result = result && getT1()
              .equals(other.getT1());
          break;
        case 2:
          result = result && getT2()
              .equals(other.getT2());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (msgCase_) {
        case 1:
          hash = (37 * hash) + T1_FIELD_NUMBER;
          hash = (53 * hash) + getT1().hashCode();
          break;
        case 2:
          hash = (37 * hash) + T2_FIELD_NUMBER;
          hash = (53 * hash) + getT2().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static udppeer.UDPPeerMessages.Packet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static udppeer.UDPPeerMessages.Packet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static udppeer.UDPPeerMessages.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static udppeer.UDPPeerMessages.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static udppeer.UDPPeerMessages.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static udppeer.UDPPeerMessages.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static udppeer.UDPPeerMessages.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static udppeer.UDPPeerMessages.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static udppeer.UDPPeerMessages.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static udppeer.UDPPeerMessages.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static udppeer.UDPPeerMessages.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static udppeer.UDPPeerMessages.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(udppeer.UDPPeerMessages.Packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Packet)
        udppeer.UDPPeerMessages.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return udppeer.UDPPeerMessages.internal_static_Packet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return udppeer.UDPPeerMessages.internal_static_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                udppeer.UDPPeerMessages.Packet.class, udppeer.UDPPeerMessages.Packet.Builder.class);
      }

      // Construct using udppeer.UDPPeerMessages.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgCase_ = 0;
        msg_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return udppeer.UDPPeerMessages.internal_static_Packet_descriptor;
      }

      public udppeer.UDPPeerMessages.Packet getDefaultInstanceForType() {
        return udppeer.UDPPeerMessages.Packet.getDefaultInstance();
      }

      public udppeer.UDPPeerMessages.Packet build() {
        udppeer.UDPPeerMessages.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public udppeer.UDPPeerMessages.Packet buildPartial() {
        udppeer.UDPPeerMessages.Packet result = new udppeer.UDPPeerMessages.Packet(this);
        if (msgCase_ == 1) {
          if (t1Builder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = t1Builder_.build();
          }
        }
        if (msgCase_ == 2) {
          if (t2Builder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = t2Builder_.build();
          }
        }
        result.msgCase_ = msgCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof udppeer.UDPPeerMessages.Packet) {
          return mergeFrom((udppeer.UDPPeerMessages.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(udppeer.UDPPeerMessages.Packet other) {
        if (other == udppeer.UDPPeerMessages.Packet.getDefaultInstance()) return this;
        switch (other.getMsgCase()) {
          case T1: {
            mergeT1(other.getT1());
            break;
          }
          case T2: {
            mergeT2(other.getT2());
            break;
          }
          case MSG_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        udppeer.UDPPeerMessages.Packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (udppeer.UDPPeerMessages.Packet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int msgCase_ = 0;
      private java.lang.Object msg_;
      public MsgCase
          getMsgCase() {
        return MsgCase.forNumber(
            msgCase_);
      }

      public Builder clearMsg() {
        msgCase_ = 0;
        msg_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          udppeer.UDPPeerMessages.Type1, udppeer.UDPPeerMessages.Type1.Builder, udppeer.UDPPeerMessages.Type1OrBuilder> t1Builder_;
      /**
       * <code>.Type1 t1 = 1;</code>
       */
      public boolean hasT1() {
        return msgCase_ == 1;
      }
      /**
       * <code>.Type1 t1 = 1;</code>
       */
      public udppeer.UDPPeerMessages.Type1 getT1() {
        if (t1Builder_ == null) {
          if (msgCase_ == 1) {
            return (udppeer.UDPPeerMessages.Type1) msg_;
          }
          return udppeer.UDPPeerMessages.Type1.getDefaultInstance();
        } else {
          if (msgCase_ == 1) {
            return t1Builder_.getMessage();
          }
          return udppeer.UDPPeerMessages.Type1.getDefaultInstance();
        }
      }
      /**
       * <code>.Type1 t1 = 1;</code>
       */
      public Builder setT1(udppeer.UDPPeerMessages.Type1 value) {
        if (t1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          t1Builder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.Type1 t1 = 1;</code>
       */
      public Builder setT1(
          udppeer.UDPPeerMessages.Type1.Builder builderForValue) {
        if (t1Builder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          t1Builder_.setMessage(builderForValue.build());
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.Type1 t1 = 1;</code>
       */
      public Builder mergeT1(udppeer.UDPPeerMessages.Type1 value) {
        if (t1Builder_ == null) {
          if (msgCase_ == 1 &&
              msg_ != udppeer.UDPPeerMessages.Type1.getDefaultInstance()) {
            msg_ = udppeer.UDPPeerMessages.Type1.newBuilder((udppeer.UDPPeerMessages.Type1) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 1) {
            t1Builder_.mergeFrom(value);
          }
          t1Builder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.Type1 t1 = 1;</code>
       */
      public Builder clearT1() {
        if (t1Builder_ == null) {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
          }
          t1Builder_.clear();
        }
        return this;
      }
      /**
       * <code>.Type1 t1 = 1;</code>
       */
      public udppeer.UDPPeerMessages.Type1.Builder getT1Builder() {
        return getT1FieldBuilder().getBuilder();
      }
      /**
       * <code>.Type1 t1 = 1;</code>
       */
      public udppeer.UDPPeerMessages.Type1OrBuilder getT1OrBuilder() {
        if ((msgCase_ == 1) && (t1Builder_ != null)) {
          return t1Builder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 1) {
            return (udppeer.UDPPeerMessages.Type1) msg_;
          }
          return udppeer.UDPPeerMessages.Type1.getDefaultInstance();
        }
      }
      /**
       * <code>.Type1 t1 = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          udppeer.UDPPeerMessages.Type1, udppeer.UDPPeerMessages.Type1.Builder, udppeer.UDPPeerMessages.Type1OrBuilder> 
          getT1FieldBuilder() {
        if (t1Builder_ == null) {
          if (!(msgCase_ == 1)) {
            msg_ = udppeer.UDPPeerMessages.Type1.getDefaultInstance();
          }
          t1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              udppeer.UDPPeerMessages.Type1, udppeer.UDPPeerMessages.Type1.Builder, udppeer.UDPPeerMessages.Type1OrBuilder>(
                  (udppeer.UDPPeerMessages.Type1) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 1;
        onChanged();;
        return t1Builder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          udppeer.UDPPeerMessages.Type2, udppeer.UDPPeerMessages.Type2.Builder, udppeer.UDPPeerMessages.Type2OrBuilder> t2Builder_;
      /**
       * <code>.Type2 t2 = 2;</code>
       */
      public boolean hasT2() {
        return msgCase_ == 2;
      }
      /**
       * <code>.Type2 t2 = 2;</code>
       */
      public udppeer.UDPPeerMessages.Type2 getT2() {
        if (t2Builder_ == null) {
          if (msgCase_ == 2) {
            return (udppeer.UDPPeerMessages.Type2) msg_;
          }
          return udppeer.UDPPeerMessages.Type2.getDefaultInstance();
        } else {
          if (msgCase_ == 2) {
            return t2Builder_.getMessage();
          }
          return udppeer.UDPPeerMessages.Type2.getDefaultInstance();
        }
      }
      /**
       * <code>.Type2 t2 = 2;</code>
       */
      public Builder setT2(udppeer.UDPPeerMessages.Type2 value) {
        if (t2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          t2Builder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.Type2 t2 = 2;</code>
       */
      public Builder setT2(
          udppeer.UDPPeerMessages.Type2.Builder builderForValue) {
        if (t2Builder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          t2Builder_.setMessage(builderForValue.build());
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.Type2 t2 = 2;</code>
       */
      public Builder mergeT2(udppeer.UDPPeerMessages.Type2 value) {
        if (t2Builder_ == null) {
          if (msgCase_ == 2 &&
              msg_ != udppeer.UDPPeerMessages.Type2.getDefaultInstance()) {
            msg_ = udppeer.UDPPeerMessages.Type2.newBuilder((udppeer.UDPPeerMessages.Type2) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 2) {
            t2Builder_.mergeFrom(value);
          }
          t2Builder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.Type2 t2 = 2;</code>
       */
      public Builder clearT2() {
        if (t2Builder_ == null) {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
          }
          t2Builder_.clear();
        }
        return this;
      }
      /**
       * <code>.Type2 t2 = 2;</code>
       */
      public udppeer.UDPPeerMessages.Type2.Builder getT2Builder() {
        return getT2FieldBuilder().getBuilder();
      }
      /**
       * <code>.Type2 t2 = 2;</code>
       */
      public udppeer.UDPPeerMessages.Type2OrBuilder getT2OrBuilder() {
        if ((msgCase_ == 2) && (t2Builder_ != null)) {
          return t2Builder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 2) {
            return (udppeer.UDPPeerMessages.Type2) msg_;
          }
          return udppeer.UDPPeerMessages.Type2.getDefaultInstance();
        }
      }
      /**
       * <code>.Type2 t2 = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          udppeer.UDPPeerMessages.Type2, udppeer.UDPPeerMessages.Type2.Builder, udppeer.UDPPeerMessages.Type2OrBuilder> 
          getT2FieldBuilder() {
        if (t2Builder_ == null) {
          if (!(msgCase_ == 2)) {
            msg_ = udppeer.UDPPeerMessages.Type2.getDefaultInstance();
          }
          t2Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              udppeer.UDPPeerMessages.Type2, udppeer.UDPPeerMessages.Type2.Builder, udppeer.UDPPeerMessages.Type2OrBuilder>(
                  (udppeer.UDPPeerMessages.Type2) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 2;
        onChanged();;
        return t2Builder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Packet)
    }

    // @@protoc_insertion_point(class_scope:Packet)
    private static final udppeer.UDPPeerMessages.Packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new udppeer.UDPPeerMessages.Packet();
    }

    public static udppeer.UDPPeerMessages.Packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Packet>
        PARSER = new com.google.protobuf.AbstractParser<Packet>() {
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Packet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Packet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    public udppeer.UDPPeerMessages.Packet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Type1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Type1_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Type2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Type2_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Packet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Packet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rudppeer.proto\"\030\n\005Type1\022\017\n\007strData\030\001 \001(" +
      "\t\"\030\n\005Type2\022\017\n\007intData\030\001 \001(\005\";\n\006Packet\022\024\n" +
      "\002t1\030\001 \001(\0132\006.Type1H\000\022\024\n\002t2\030\002 \001(\0132\006.Type2H" +
      "\000B\005\n\003msgB\032\n\007udppeerB\017UDPPeerMessagesb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Type1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Type1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Type1_descriptor,
        new java.lang.String[] { "StrData", });
    internal_static_Type2_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Type2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Type2_descriptor,
        new java.lang.String[] { "IntData", });
    internal_static_Packet_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Packet_descriptor,
        new java.lang.String[] { "T1", "T2", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
