// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: udppeer.proto

package udppeer;

public final class UDPPeerMessages {
  private UDPPeerMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Packet.Type type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.Packet.Type type = 1;</code>
     */
    udppeer.UDPPeerMessages.Packet.Type getType();

    /**
     * <code>string strData = 2;</code>
     */
    java.lang.String getStrData();
    /**
     * <code>string strData = 2;</code>
     */
    com.google.protobuf.ByteString
        getStrDataBytes();

    /**
     * <code>int32 intData = 3;</code>
     */
    int getIntData();
  }
  /**
   * Protobuf type {@code Packet}
   */
  public  static final class Packet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Packet)
      PacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Packet() {
      type_ = 0;
      strData_ = "";
      intData_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              strData_ = s;
              break;
            }
            case 24: {

              intData_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return udppeer.UDPPeerMessages.internal_static_Packet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return udppeer.UDPPeerMessages.internal_static_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              udppeer.UDPPeerMessages.Packet.class, udppeer.UDPPeerMessages.Packet.Builder.class);
    }

    /**
     * Protobuf enum {@code Packet.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TYPE1 = 0;</code>
       */
      TYPE1(0),
      /**
       * <code>TYPE2 = 1;</code>
       */
      TYPE2(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>TYPE1 = 0;</code>
       */
      public static final int TYPE1_VALUE = 0;
      /**
       * <code>TYPE2 = 1;</code>
       */
      public static final int TYPE2_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 0: return TYPE1;
          case 1: return TYPE2;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return udppeer.UDPPeerMessages.Packet.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Packet.Type)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.Packet.Type type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.Packet.Type type = 1;</code>
     */
    public udppeer.UDPPeerMessages.Packet.Type getType() {
      udppeer.UDPPeerMessages.Packet.Type result = udppeer.UDPPeerMessages.Packet.Type.valueOf(type_);
      return result == null ? udppeer.UDPPeerMessages.Packet.Type.UNRECOGNIZED : result;
    }

    public static final int STRDATA_FIELD_NUMBER = 2;
    private volatile java.lang.Object strData_;
    /**
     * <code>string strData = 2;</code>
     */
    public java.lang.String getStrData() {
      java.lang.Object ref = strData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        strData_ = s;
        return s;
      }
    }
    /**
     * <code>string strData = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStrDataBytes() {
      java.lang.Object ref = strData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTDATA_FIELD_NUMBER = 3;
    private int intData_;
    /**
     * <code>int32 intData = 3;</code>
     */
    public int getIntData() {
      return intData_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != udppeer.UDPPeerMessages.Packet.Type.TYPE1.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!getStrDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, strData_);
      }
      if (intData_ != 0) {
        output.writeInt32(3, intData_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != udppeer.UDPPeerMessages.Packet.Type.TYPE1.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!getStrDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, strData_);
      }
      if (intData_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, intData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof udppeer.UDPPeerMessages.Packet)) {
        return super.equals(obj);
      }
      udppeer.UDPPeerMessages.Packet other = (udppeer.UDPPeerMessages.Packet) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getStrData()
          .equals(other.getStrData());
      result = result && (getIntData()
          == other.getIntData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + STRDATA_FIELD_NUMBER;
      hash = (53 * hash) + getStrData().hashCode();
      hash = (37 * hash) + INTDATA_FIELD_NUMBER;
      hash = (53 * hash) + getIntData();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static udppeer.UDPPeerMessages.Packet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static udppeer.UDPPeerMessages.Packet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static udppeer.UDPPeerMessages.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static udppeer.UDPPeerMessages.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static udppeer.UDPPeerMessages.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static udppeer.UDPPeerMessages.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static udppeer.UDPPeerMessages.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static udppeer.UDPPeerMessages.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static udppeer.UDPPeerMessages.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static udppeer.UDPPeerMessages.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static udppeer.UDPPeerMessages.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static udppeer.UDPPeerMessages.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(udppeer.UDPPeerMessages.Packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Packet)
        udppeer.UDPPeerMessages.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return udppeer.UDPPeerMessages.internal_static_Packet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return udppeer.UDPPeerMessages.internal_static_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                udppeer.UDPPeerMessages.Packet.class, udppeer.UDPPeerMessages.Packet.Builder.class);
      }

      // Construct using udppeer.UDPPeerMessages.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        strData_ = "";

        intData_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return udppeer.UDPPeerMessages.internal_static_Packet_descriptor;
      }

      public udppeer.UDPPeerMessages.Packet getDefaultInstanceForType() {
        return udppeer.UDPPeerMessages.Packet.getDefaultInstance();
      }

      public udppeer.UDPPeerMessages.Packet build() {
        udppeer.UDPPeerMessages.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public udppeer.UDPPeerMessages.Packet buildPartial() {
        udppeer.UDPPeerMessages.Packet result = new udppeer.UDPPeerMessages.Packet(this);
        result.type_ = type_;
        result.strData_ = strData_;
        result.intData_ = intData_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof udppeer.UDPPeerMessages.Packet) {
          return mergeFrom((udppeer.UDPPeerMessages.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(udppeer.UDPPeerMessages.Packet other) {
        if (other == udppeer.UDPPeerMessages.Packet.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getStrData().isEmpty()) {
          strData_ = other.strData_;
          onChanged();
        }
        if (other.getIntData() != 0) {
          setIntData(other.getIntData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        udppeer.UDPPeerMessages.Packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (udppeer.UDPPeerMessages.Packet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.Packet.Type type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.Packet.Type type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Packet.Type type = 1;</code>
       */
      public udppeer.UDPPeerMessages.Packet.Type getType() {
        udppeer.UDPPeerMessages.Packet.Type result = udppeer.UDPPeerMessages.Packet.Type.valueOf(type_);
        return result == null ? udppeer.UDPPeerMessages.Packet.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.Packet.Type type = 1;</code>
       */
      public Builder setType(udppeer.UDPPeerMessages.Packet.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Packet.Type type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object strData_ = "";
      /**
       * <code>string strData = 2;</code>
       */
      public java.lang.String getStrData() {
        java.lang.Object ref = strData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          strData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string strData = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStrDataBytes() {
        java.lang.Object ref = strData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          strData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string strData = 2;</code>
       */
      public Builder setStrData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        strData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string strData = 2;</code>
       */
      public Builder clearStrData() {
        
        strData_ = getDefaultInstance().getStrData();
        onChanged();
        return this;
      }
      /**
       * <code>string strData = 2;</code>
       */
      public Builder setStrDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        strData_ = value;
        onChanged();
        return this;
      }

      private int intData_ ;
      /**
       * <code>int32 intData = 3;</code>
       */
      public int getIntData() {
        return intData_;
      }
      /**
       * <code>int32 intData = 3;</code>
       */
      public Builder setIntData(int value) {
        
        intData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 intData = 3;</code>
       */
      public Builder clearIntData() {
        
        intData_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Packet)
    }

    // @@protoc_insertion_point(class_scope:Packet)
    private static final udppeer.UDPPeerMessages.Packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new udppeer.UDPPeerMessages.Packet();
    }

    public static udppeer.UDPPeerMessages.Packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Packet>
        PARSER = new com.google.protobuf.AbstractParser<Packet>() {
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Packet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Packet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    public udppeer.UDPPeerMessages.Packet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Packet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Packet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rudppeer.proto\"d\n\006Packet\022\032\n\004type\030\001 \001(\0162" +
      "\014.Packet.Type\022\017\n\007strData\030\002 \001(\t\022\017\n\007intDat" +
      "a\030\003 \001(\005\"\034\n\004Type\022\t\n\005TYPE1\020\000\022\t\n\005TYPE2\020\001B\032\n" +
      "\007udppeerB\017UDPPeerMessagesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Packet_descriptor,
        new java.lang.String[] { "Type", "StrData", "IntData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
